target-version = "py310"
line-length = 120
extend-exclude = [
    "*/_vendored/*",
    "*/schema/generated/*",
    "packages/hca-anndata-tools/src/hca_anndata_tools/schema/core.py",
]

[lint]
select = ["E", "F", "I", "W"]
