name: Publish hca-schema-validator to PyPI

on:
  release:
    types: [published]
  workflow_dispatch:  # Allow manual re-publishing of latest release

permissions:
  contents: read
  id-token: write  # Required for trusted publishing

jobs:
  publish:

    # Run for hca-schema-validator releases or manual trigger
    if: github.event_name == 'workflow_dispatch' || startsWith(github.event.release.tag_name, 'hca-schema-validator-v')
    runs-on: ubuntu-latest
    
    steps:
      - name: Log trigger info
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Release tag: ${{ github.event.release.tag_name }}"
          echo "Ref: ${{ github.ref }}"
      
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      
      - name: Build package
        run: |
          cd packages/hca-schema-validator
          poetry build
      
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: packages/hca-schema-validator/dist/
